trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: TestDev
  displayName: Trigger dev notebook
  jobs:
  - job: Execute
    steps:

    - checkout: self

    - task: AzureCLI@2
      displayName: "Run Python Script"
      inputs:
        azureSubscription: 'Rest'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          python3 -m pip install --upgrade pip

          pip install azure-identity
          pip install requests

          echo "Running Python script..."
          python3 verify.py

    - task: AzureCLI@2
      displayName: "Run Fabric cli"
      inputs:
        azureSubscription: 'Rest'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Using Python $(python --version)"

          # Install Python and dependencies
          python3 -m pip install --upgrade pip

          pip install ms-fabric-cli

          fab config set encryption_fallback_enabled true
          fab auth login -u 0e0feaeb-874c-449c-921a-716555c2b903 -p $(sp_secret) --tenant 9891b9df-58a3-4626-8a97-d93855fff2f1

          fab auth status

          fab job run dev.Workspace/silver_views.Notebook
